/**
 * AeroTwin-UAV Engine Components Catalog
 * Master definitions for the 20 major aero piston engine components (Rotax 914/915 Boxer-4 style).
 * Maps parts to functional descriptions, normal engineering operating ranges,
 * and live telemetry channel bindings.
 */

export const ENGINE_PARTS = [
  {
    id: 'propeller',
    name: 'Propeller',
    category: 'Propulsion',
    function: 'Converts engine shaft torque into aerodynamic thrust for UAV flight propulsion.',
    telemetryKey: 'rpm',
    telemetryLabel: 'Propeller / Engine Speed',
    unit: 'RPM',
    nominalMin: 1800,
    nominalMax: 2550,
    warningMax: 2650,
    normalRange: '1,800 - 2,550 RPM',
    color: '#334155', // Dark metallic
    explodedOffset: [0, 0, 1.6],
    schematicPos: { x: 50, y: 150 },
  },
  {
    id: 'propeller_hub',
    name: 'Propeller Hub',
    category: 'Propulsion',
    function: 'Houses propeller blade mounting retention pins and mechanical reduction pitch assembly.',
    telemetryKey: 'vibration',
    telemetryLabel: 'Shaft Vibration',
    unit: 'g',
    nominalMin: 0.5,
    nominalMax: 3.5,
    warningMax: 5.0,
    normalRange: '0.5 - 3.5 g',
    color: '#475569',
    explodedOffset: [0, 0, 1.2],
    schematicPos: { x: 105, y: 150 },
  },
  {
    id: 'crankshaft',
    name: 'Crankshaft',
    category: 'Mechanical Core',
    function: 'Transforms linear reciprocating motion of the 4 opposed pistons into rotational torque.',
    telemetryKey: 'rpm',
    telemetryLabel: 'Engine Speed',
    unit: 'RPM',
    nominalMin: 1800,
    nominalMax: 2550,
    warningMax: 2650,
    normalRange: '1,800 - 2,550 RPM',
    color: '#94a3b8',
    explodedOffset: [0, 0, 0],
    schematicPos: { x: 260, y: 150 },
  },
  {
    id: 'crankcase',
    name: 'Crankcase',
    category: 'Structural Core',
    function: 'Main structural split aluminum housing containing the crankshaft, camshaft, and oil galleries.',
    telemetryKey: 'engine_load',
    telemetryLabel: 'Engine Load Factor',
    unit: '%',
    nominalMin: 40,
    nominalMax: 85,
    warningMax: 95,
    normalRange: '40.0 - 85.0 %',
    color: '#1e293b', // Metallic dark gray
    explodedOffset: [0, 0, 0],
    schematicPos: { x: 260, y: 150 },
  },
  {
    id: 'cylinder_1',
    name: 'Cylinder 1',
    category: 'Combustion Chamber',
    function: 'Forward left-bank combustion cylinder barrel with Nicasil ceramic liner coating.',
    telemetryKey: 'cht',
    telemetryLabel: 'Cylinder Head Temp',
    unit: '°C',
    nominalMin: 80,
    nominalMax: 135,
    warningMax: 150,
    normalRange: '80.0 - 135.0 °C',
    color: '#64748b',
    explodedOffset: [-1.2, 0, 0.4],
    schematicPos: { x: 220, y: 80 },
  },
  {
    id: 'cylinder_2',
    name: 'Cylinder 2',
    category: 'Combustion Chamber',
    function: 'Aft left-bank combustion cylinder barrel with Nicasil ceramic liner coating.',
    telemetryKey: 'cht',
    telemetryLabel: 'Cylinder Head Temp',
    unit: '°C',
    nominalMin: 80,
    nominalMax: 135,
    warningMax: 150,
    normalRange: '80.0 - 135.0 °C',
    color: '#64748b',
    explodedOffset: [-1.2, 0, -0.4],
    schematicPos: { x: 300, y: 80 },
  },
  {
    id: 'cylinder_3',
    name: 'Cylinder 3',
    category: 'Combustion Chamber',
    function: 'Forward right-bank combustion cylinder barrel with Nicasil ceramic liner coating.',
    telemetryKey: 'cht',
    telemetryLabel: 'Cylinder Head Temp',
    unit: '°C',
    nominalMin: 80,
    nominalMax: 135,
    warningMax: 150,
    normalRange: '80.0 - 135.0 °C',
    color: '#64748b',
    explodedOffset: [1.2, 0, 0.4],
    schematicPos: { x: 220, y: 220 },
  },
  {
    id: 'cylinder_4',
    name: 'Cylinder 4',
    category: 'Combustion Chamber',
    function: 'Aft right-bank combustion cylinder barrel with Nicasil ceramic liner coating.',
    telemetryKey: 'cht',
    telemetryLabel: 'Cylinder Head Temp',
    unit: '°C',
    nominalMin: 80,
    nominalMax: 135,
    warningMax: 150,
    normalRange: '80.0 - 135.0 °C',
    color: '#64748b',
    explodedOffset: [1.2, 0, -0.4],
    schematicPos: { x: 300, y: 220 },
  },
  {
    id: 'cylinder_head',
    name: 'Cylinder Head',
    category: 'Thermal / Combustion',
    function: 'Liquid/air dual-cooled heads housing overhead intake and exhaust valves.',
    telemetryKey: 'cht',
    telemetryLabel: 'Head Temp (CHT)',
    unit: '°C',
    nominalMin: 80,
    nominalMax: 135,
    warningMax: 150,
    normalRange: '80.0 - 135.0 °C',
    color: '#cbd5e1', // Metallic silver
    explodedOffset: [-1.8, 0, 0],
    schematicPos: { x: 260, y: 50 },
  },
  {
    id: 'piston',
    name: 'Piston',
    category: 'Mechanical Core',
    function: 'Forged aluminum alloy piston with compression and oil scraper rings reciprocating in cylinder.',
    telemetryKey: 'engine_load',
    telemetryLabel: 'Dynamic Piston Load',
    unit: '%',
    nominalMin: 40,
    nominalMax: 85,
    warningMax: 95,
    normalRange: '40.0 - 85.0 %',
    color: '#e2e8f0', // Metallic light gray
    explodedOffset: [-0.6, 0, 0],
    schematicPos: { x: 260, y: 110 },
  },
  {
    id: 'intake_manifold',
    name: 'Intake Manifold',
    category: 'Fuel & Air Induction',
    function: 'Equalized induction runners routing pressurized air-fuel mixture to intake valve ports.',
    telemetryKey: 'fuel_flow',
    telemetryLabel: 'Fuel/Air Induction Flow',
    unit: 'L/h',
    nominalMin: 18,
    nominalMax: 35,
    warningMax: 42,
    normalRange: '18.0 - 35.0 L/h',
    color: '#ea580c', // Orange/red
    explodedOffset: [0, 0.9, 0],
    schematicPos: { x: 360, y: 150 },
  },
  {
    id: 'air_intake',
    name: 'Air Intake',
    category: 'Induction',
    function: 'Dynamic ram air scoop and particulate filter feeding turbocharger compressor inlet.',
    telemetryKey: 'engine_load',
    telemetryLabel: 'Manifold Air Pressure',
    unit: '%',
    nominalMin: 40,
    nominalMax: 85,
    warningMax: 95,
    normalRange: '40.0 - 85.0 %',
    color: '#f97316',
    explodedOffset: [0, 1.2, -0.8],
    schematicPos: { x: 420, y: 150 },
  },
  {
    id: 'fuel_injector',
    name: 'Fuel Injector',
    category: 'Fuel System',
    function: 'Multi-hole solenoid electronic injector atomizing fuel into the intake runner at high pressure.',
    telemetryKey: 'fuel_flow',
    telemetryLabel: 'Fuel Flow Rate',
    unit: 'L/h',
    nominalMin: 18,
    nominalMax: 35,
    warningMax: 42,
    normalRange: '18.0 - 35.0 L/h',
    color: '#ef4444',
    explodedOffset: [-0.4, 0.8, 0.3],
    schematicPos: { x: 340, y: 110 },
  },
  {
    id: 'fuel_system',
    name: 'Fuel System',
    category: 'Fuel System',
    function: 'Dual redundant electronic fuel rail, manifold regulator, and high-pressure electric feed pumps.',
    telemetryKey: 'fuel_flow',
    telemetryLabel: 'System Fuel Delivery',
    unit: 'L/h',
    nominalMin: 18,
    nominalMax: 35,
    warningMax: 42,
    normalRange: '18.0 - 35.0 L/h',
    color: '#dc2626',
    explodedOffset: [0, 0.7, 0.6],
    schematicPos: { x: 340, y: 190 },
  },
  {
    id: 'ignition_system',
    name: 'Ignition System',
    category: 'Electrical / Ignition',
    function: 'Dual capacitor discharge ignition (CDI) modules supplying synchronized high-voltage timing pulses.',
    telemetryKey: 'rpm',
    telemetryLabel: 'Ignition Trigger Timing',
    unit: 'RPM',
    nominalMin: 1800,
    nominalMax: 2550,
    warningMax: 2650,
    normalRange: 'Dual CDI Active',
    color: '#b91c1c', // Red
    explodedOffset: [0, 0.8, -0.6],
    schematicPos: { x: 180, y: 80 },
  },
  {
    id: 'spark_plug',
    name: 'Spark Plug',
    category: 'Electrical / Ignition',
    function: 'Dual spark plugs per cylinder for complete flame-front propagation and redundant safety.',
    telemetryKey: 'cht',
    telemetryLabel: 'Electrode Temp (CHT)',
    unit: '°C',
    nominalMin: 80,
    nominalMax: 135,
    warningMax: 150,
    normalRange: '80.0 - 135.0 °C',
    color: '#f87171',
    explodedOffset: [-1.4, 0.5, 0],
    schematicPos: { x: 180, y: 50 },
  },
  {
    id: 'exhaust_manifold',
    name: 'Exhaust Manifold',
    category: 'Exhaust / Thermal',
    function: 'Inconel stainless tuned exhaust header pipes driving turbocharger exhaust turbine wheel.',
    telemetryKey: 'egt',
    telemetryLabel: 'Exhaust Gas Temp (EGT)',
    unit: '°C',
    nominalMin: 720,
    nominalMax: 840,
    warningMax: 880,
    normalRange: '720.0 - 840.0 °C',
    color: '#78350f', // Dark metallic with heat tint
    explodedOffset: [0, -1.1, -1.0],
    schematicPos: { x: 420, y: 220 },
  },
  {
    id: 'oil_filter',
    name: 'Oil Filter',
    category: 'Lubrication',
    function: 'Full-flow spin-on micro-filtration canister removing metallic particles and combustion debris.',
    telemetryKey: 'oil_pressure',
    telemetryLabel: 'Differential Oil P',
    unit: 'bar',
    nominalMin: 2.0,
    nominalMax: 4.5,
    warningMax: 5.5,
    normalRange: '2.0 - 4.5 bar',
    color: '#eab308', // Yellow/gold
    explodedOffset: [0.7, -0.8, 0.5],
    schematicPos: { x: 180, y: 220 },
  },
  {
    id: 'oil_system',
    name: 'Oil System',
    category: 'Lubrication',
    function: 'Dry sump lubrication network with external oil cooler, tank, and positive-displacement scavenge pump.',
    telemetryKey: 'oil_temperature',
    telemetryLabel: 'Oil Temperature',
    unit: '°C',
    nominalMin: 75,
    nominalMax: 110,
    warningMax: 125,
    normalRange: '75.0 - 110.0 °C',
    color: '#ca8a04', // Yellow/gold
    explodedOffset: [0, -0.9, 0],
    schematicPos: { x: 260, y: 250 },
  },
  {
    id: 'cooling_fins',
    name: 'Cooling Fins',
    category: 'Thermal Management',
    function: 'Radial aluminum heat-dissipation fin arrays on cylinder barrels for ram-air thermal convective transfer.',
    telemetryKey: 'cht',
    telemetryLabel: 'Fin Thermal Convection',
    unit: '°C',
    nominalMin: 80,
    nominalMax: 135,
    warningMax: 150,
    normalRange: '80.0 - 135.0 °C',
    color: '#94a3b8', // Silver
    explodedOffset: [-1.0, 0, 0],
    schematicPos: { x: 180, y: 150 },
  },
  {
    id: 'connecting_rod',
    name: 'Connecting Rod',
    category: 'Kinematic Link',
    function: 'Forged H-beam connecting rod transferring reciprocating linear force from piston wrist pin to crankshaft throw journal.',
    telemetryKey: 'vibration',
    telemetryLabel: 'Rod / Journal Vibration',
    unit: 'g',
    nominalMin: 0.5,
    nominalMax: 3.5,
    warningMax: 5.0,
    normalRange: '0.5 - 3.5 g',
    color: '#94a3b8',
    explodedOffset: [-0.4, 0, 0],
    schematicPos: { x: 260, y: 130 },
  },
  {
    id: 'intake_valve',
    name: 'Intake Valve',
    category: 'Valvetrain',
    function: 'Precision poppet valve opening during INTAKE stroke to admit pressurized atomized fuel/air charge.',
    telemetryKey: 'engine_load',
    telemetryLabel: 'Volumetric Efficiency',
    unit: '%',
    nominalMin: 40,
    nominalMax: 85,
    warningMax: 95,
    normalRange: '40.0 - 85.0 %',
    color: '#38bdf8',
    explodedOffset: [-1.6, 0.3, 0],
    schematicPos: { x: 320, y: 50 },
  },
  {
    id: 'exhaust_valve',
    name: 'Exhaust Valve',
    category: 'Valvetrain',
    function: 'High-nickel heat-resistant poppet valve opening during EXHAUST stroke to evacuate burned gases.',
    telemetryKey: 'egt',
    telemetryLabel: 'Valve Gas Temp',
    unit: '°C',
    nominalMin: 720,
    nominalMax: 840,
    warningMax: 880,
    normalRange: '720.0 - 840.0 °C',
    color: '#ea580c',
    explodedOffset: [-1.6, -0.3, 0],
    schematicPos: { x: 380, y: 50 },
  },
  {
    id: 'rocker_arm',
    name: 'Rocker Arm & Pushrod',
    category: 'Valvetrain',
    function: 'Actuates overhead valves from camshaft via hydraulic lifters and hardened spherical pushrods.',
    telemetryKey: 'rpm',
    telemetryLabel: 'Valvetrain Cycle Speed',
    unit: 'RPM',
    nominalMin: 1800,
    nominalMax: 2550,
    warningMax: 2650,
    normalRange: '1,800 - 2,550 RPM',
    color: '#64748b',
    explodedOffset: [-1.7, 0.4, 0],
    schematicPos: { x: 350, y: 35 },
  },
];

/**
 * Computes component operational status given live telemetry & digital twin state
 * @returns {'HEALTHY' | 'WARNING' | 'CRITICAL'}
 */
export function getComponentStatus(part, telemetry = {}, digitalTwin = {}) {
  if (!telemetry || Object.keys(telemetry).length === 0) {
    return 'HEALTHY';
  }

  const val = telemetry[part.telemetryKey];
  if (val === undefined || val === null || isNaN(val)) {
    return 'HEALTHY';
  }

  // Check critical thresholds
  if (part.warningMax && val >= part.warningMax) {
    return 'CRITICAL';
  }
  if (part.nominalMin && val < part.nominalMin * 0.85) {
    return 'CRITICAL';
  }

  // Check warning thresholds
  if (part.nominalMax && val > part.nominalMax) {
    return 'WARNING';
  }
  if (part.nominalMin && val < part.nominalMin) {
    return 'WARNING';
  }

  // Check general digital twin deviations if available
  const deviations = digitalTwin?.deviations || {};
  if (deviations[part.telemetryKey]) {
    const devStatus = deviations[part.telemetryKey].status;
    if (devStatus === 'CRITICAL') return 'CRITICAL';
    if (devStatus === 'WARNING') return 'WARNING';
  }

  return 'HEALTHY';
}
